### ISSUE TITLE
Localization disaster

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-calendars#10]
Hello,

we are using "@syncfusion/ej2-ng-calendars": "16.2.47" in our project.

Because our buisness is in germany we need an german date format. The attribute locale doesn't work. I tried to set this attribute with [locale]="de" and locale="de" but both are not working. In your api stands, that the attribute is string so locale="de" should work. I always see an american date format.

Now in ej2-ng-grid the german date format works.

What is the problem? Why there are always new problems with the localization?

Need help.

Regards
LastCodeDE

**Comment by DeepaLoganathan** [comment]
Hi @LastCodeDE ,  


Thanks for your interest in Syncfusion products. 

 
We have tested Datepicker control against German culture with a simple sample by setting both the locale of Datepicker control and by using the setCulture method in our application and can confirm that the component is working fine to display the value in textbox based on the culture settings (German).  
 
 
Please find the sample we did try at our end.  

 
Plunker: https://plnkr.co/edit/8VKpMrXU9G09XCyaBCw3?p=preview 
 
 
In addition to that, we suspect that the issue might occur when 
 
 
1.	The CLDR Json data of German culture is not loaded in the application
 
2.	Dateformat of the Calendar component is different from that of the default formats accepted in German culture i.e. format other than the below. 

> We suggest using the Date input to Calendar as Date object instead of String type. 

 
 ```

"dateFormats": { 
              "full": "EEEE, d. MMMM y", 
              "long": "d. MMMM y", 
              "medium": "dd.MM.y", 
              "short": "dd.MM.yy" 
            }, 

```
   
3.	JSON plugin loader to load the CLDR JSON data is not properly installed or loaded in the application.
 
 
So kindly check the above-mentioned points to check for the probable causes of the issue and please check our below help pages to explore more about achieving Globalization in Calendar. 


https://ej2.syncfusion.com/angular/documentation/calendar/globalization 

 
Regards,  

Deepa L.
