### ISSUE TITLE
use one of the presets as default 

### ISSUE THREAD

**Issue by hamdiwanis** [syncfusion/ej2-ng-calendars#8]
hello, I was wondering if it's possible to use one of the presets as default for range fate picker. thanks

**Comment by ThirukumanaranM** [comment]
Hi Hamdiwanis, 
 
Thanks for your interest in Essential JS 2. 
 
We have looked into your query “use one of the presets as default” and you can achieve this requirement by using the “startDate” and “endDate” properties of DateRangePicker. So, we suggest you to try the below code example. 
 ```
@Component({ 
        selector: 'my-app', 
        template: `<ej-daterangepicker id="date" [presets]='presets'placeholder='Select a range' [startDate]='start' [endDate]='end'(created)='onCreate($event)'></ej-daterangepicker>`, 
    }) 
export class AppComponent  {  
  
    public presets: PresetsArgs[] = [ 
      { label: 'Today', start: new Date(), end: new Date() }, 
      { label: 'This Month', start: new Date(new Date().setDate(1)), end: new Date() }, 
      { label: 'Last Month', start: new Date(new Date(new Date().setMonth(newDate().getMonth() - 1)).setDate(1)), end: new Date() }, 
      { label: 'Last Year', start: new Date(new Date().getFullYear() - 1, 0, 1), end: new Date() }, 
    ] 
    public start: Date=this.presets[0].start; //to set the first value of the first presets as startDate 
    public end:Date=this.presets[0].start; // to set the second value of the first prestes as endDate 
} 
 
 ```
For your convenience, we have prepared the sample based on your requirement. Please get the sample from the below location. 
 
Sample Link: http://plnkr.co/edit/8flJlxVkmamZOST1druT?p=preview 
 
To know more about DateRangePicker component, please refer the below UG documentation link. 
 
UG Link: http://npmci.syncfusion.com/production/angular/documentation/daterangepicker/getting-started.html#setting-the-start-and-end-date 
 
Also, while using the presets value as startDate and endDate in the DateRangePicker component, the corresponding preset button in the preset item is not highlighted which is known issue at our end. We have fixed this issue internally and this fix will be included in our upcoming Volume 1 Release which is expected to be rolled out by end of this week.

**Comment by hamdiwanis** [comment]
thanks for your help, and actually what i meant was the highlight problem so glad it will be fixed soon
