### ISSUE TITLE
datepicker property width="12em" doesn't work with new Version 16.1.28

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-calendars#9]
Hi,

with the old version the property width="12em" works. With the new Version not.

Why?

Regards
j.nord

**Comment by Sureshkumar2288** [comment]
Hi @j-nord ,

Sorry for inconvenience. 

Yes, we can reproduce the reported issue and confirm this as a defect.  We have resolved this issue and the fix is included in our latest version. So, please make use of the updated packages to resolve this issue at your end
 

Regards,
Sureshkumar P
